// Real past/current resolutions per event — ported verbatim from public/drill-topics.js.
// Shape: { season, when (null for yearlong/unknown), text }.

export type DrillTopic = { season: string; when: string | null; text: string }

export const DRILL_TOPICS: Record<string, DrillTopic[]> = {
  "Public Forum": [
    { season: "2025-26", when: "Nationals", text: "Resolved: The United States is justified in using force to remove authoritarian leaders from power." },
    { season: "2025-26", when: "April", text: "Resolved: The United States should eliminate the President's authority to deploy military forces abroad without Congressional approval." },
    { season: "2025-26", when: "March", text: "Resolved: The United States federal government should ban corporate acquisition of single-family residences." },
    { season: "2025-26", when: "February", text: "Resolved: The Federal Trade Commission should establish a federal regulatory framework for sports betting." },
    { season: "2025-26", when: "January", text: "Resolved: The People's Republic of China should substantially reduce its international extraction of natural resources." },
    { season: "2025-26", when: "November/December", text: "Resolved: The United States federal government should require technology companies to provide lawful access to encrypted communications." },
    { season: "2025-26", when: "September/October", text: "Resolved: The United Kingdom should rejoin the European Union." },
    { season: "2024-25", when: "Nationals", text: "Resolved: On balance, in the United States, the benefits of presidential executive orders outweigh the harms." },
    { season: "2024-25", when: "April", text: "Resolved: The United States federal government should substantially increase its investment in domestic nuclear energy." },
    { season: "2024-25", when: "March", text: "Resolved: In the United States, the benefits of the use of generative artificial intelligence in education outweigh the harms." },
    { season: "2024-25", when: "February", text: "Resolved: The United States should accede to the Rome Statute of the International Criminal Court." },
    { season: "2024-25", when: "January", text: "Resolved: The African Union should grant diplomatic recognition to the Republic of Somaliland as an independent state." },
    { season: "2024-25", when: "November/December", text: "Resolved: The United States should substantially reduce its military support of Taiwan." },
    { season: "2024-25", when: "September/October", text: "Resolved: The United States federal government should substantially expand its surveillance infrastructure along its southern border." },
    { season: "2023-24", when: "Nationals", text: "Resolved: The United States should establish a comprehensive bilateral trade agreement with the European Union." },
    { season: "2023-24", when: "April", text: "Resolved: The United Nations should abolish permanent membership on its Security Council." },
    { season: "2023-24", when: "March", text: "Resolved: In the United States, collegiate student-athletes should be classified as employees of their educational institution." },
    { season: "2023-24", when: "February", text: "Resolved: The United States federal government should ban single-use plastics." },
    { season: "2023-24", when: "January", text: "Resolved: The United States federal government should repeal Section 230 of the Communications Decency Act." },
    { season: "2023-24", when: "November/December", text: "Resolved: The United States federal government should forgive all federal student loan debt." },
    { season: "2023-24", when: "September/October", text: "Resolved: The United States federal government should substantially increase its military presence in the Arctic." },
    { season: "2022-23", when: "Nationals", text: "Resolved: The United States should adopt ranked-choice voting for its federal elections." },
    { season: "2022-23", when: "April", text: "Resolved: The United States Federal Government should ban the collection of personal data through biometric recognition technology." },
    { season: "2022-23", when: "March", text: "Resolved: The Republic of India should sign the Artemis Accords." },
    { season: "2022-23", when: "February", text: "Resolved: In the United States, right-to-work laws do more harm than good." },
    { season: "2022-23", when: "January", text: "Resolved: The United States Federal Government should increase its diplomatic efforts to peacefully resolve internal armed conflicts in West Asia." },
    { season: "2022-23", when: "November/December", text: "Resolved: The United States' strategy of Great Power Competition produces more benefits than harms." },
    { season: "2022-23", when: "September/October", text: "Resolved: The United States Federal Government should substantially increase its investment in high-speed rail." },
    { season: "2021-22", when: "Nationals", text: "Resolved: The United States should establish a comprehensive bilateral trade agreement with Taiwan." },
    { season: "2021-22", when: "April", text: "Resolved: Japan should revise Article 9 of its Constitution to develop offensive military capabilities." },
    { season: "2021-22", when: "March", text: "Resolved: In the United States, the benefits of increasing organic agriculture outweigh the harms." },
    { season: "2021-22", when: "February", text: "Resolved: On balance, Turkey's membership is beneficial to the North Atlantic Treaty Organization." },
    { season: "2021-22", when: "January", text: "Resolved: The United States federal government should legalize all illicit drugs." },
    { season: "2021-22", when: "November/December", text: "Resolved: Increased United States federal regulation of cryptocurrency transactions and/or assets will produce more benefits than harms." },
    { season: "2021-22", when: "September/October", text: "Resolved: The North Atlantic Treaty Organization should substantially increase its defense commitments to the Baltic states." },
    { season: "2020-21", when: "Nationals", text: "Resolved: In the United States, social media is beneficial for democratic values." },
    { season: "2020-21", when: "April", text: "Resolved: The benefits of the International Monetary Fund outweigh the harms." },
    { season: "2020-21", when: "March", text: "Resolved: On balance, the benefits of creating the United States Space Force outweigh the harms." },
    { season: "2020-21", when: "February", text: "Resolved: On balance, the benefits of urbanization in West Africa outweigh the harms." },
    { season: "2020-21", when: "January", text: "Resolved: The National Security Agency should end its surveillance of U.S. citizens and lawful permanent residents." },
    { season: "2020-21", when: "November/December", text: "Resolved: The United States should adopt a declaratory nuclear policy of no first use." },
    { season: "2020-21", when: "September/October", text: "Resolved: The United States federal government should enact the Medicare-For-All Act of 2019." },
    { season: "2019-20", when: "Nationals", text: "Resolved: On balance, charter schools are beneficial to the quality of education in the United States." },
    { season: "2019-20", when: "April", text: "Resolved: The United States should remove nearly all of its military presence in the Arab States of the Persian Gulf." },
    { season: "2019-20", when: "March", text: "Resolved: The United States should increase its use of nuclear energy for commercial energy production." },
    { season: "2019-20", when: "February", text: "Resolved: The United States should replace means-tested welfare programs with a universal basic income." },
    { season: "2019-20", when: "January", text: "Resolved: The United States should end its economic sanctions against Venezuela." },
    { season: "2019-20", when: "November/December", text: "Resolved: The benefits of the United States federal government's use of offensive cyber operations outweigh the harms." },
    { season: "2019-20", when: "September/October", text: "Resolved: The European Union should join the Belt and Road Initiative." },
    { season: "2018-19", when: "Nationals", text: "Resolved: The United States federal government should enforce antitrust regulations on technology giants." },
    { season: "2018-19", when: "April", text: "Resolved: The United Nations should grant India permanent membership on the Security Council." },
    { season: "2018-19", when: "March", text: "Resolved: The United States should promote the development of market rate housing in urban neighborhoods." },
    { season: "2018-19", when: "February", text: "Resolved: The United States should end its arms sales to Saudi Arabia." },
    { season: "2018-19", when: "January", text: "Resolved: The United States federal government should prioritize reducing the federal debt over promoting economic growth." },
    { season: "2018-19", when: "November/December", text: "Resolved: The United States federal government should impose price controls on the pharmaceutical industry." },
    { season: "2018-19", when: "September/October", text: "Resolved: The United States should accede to the United Nations Convention on the Law of the Sea without reservations." },
    { season: "2017-18", when: "Nationals", text: "Resolved: On balance, the benefits of United States participation in the North American Free Trade Agreement outweigh the consequences." },
    { season: "2017-18", when: "April", text: "Resolved: The United States federal government should increase its quota of H-1B visas." },
    { season: "2017-18", when: "March", text: "Resolved: On balance, the current Authorization for Use of Military Force gives too much power to the president." },
    { season: "2017-18", when: "February", text: "Resolved: The United States should abolish the capital gains tax." },
    { season: "2017-18", when: "January", text: "Resolved: Spain should grant Catalonia its independence." },
    { season: "2017-18", when: "December", text: "Resolved: NCAA student athletes ought to be recognized as employees under the Fair Labor Standards Act." },
    { season: "2017-18", when: "November", text: "Resolved: The United States should require universal background checks for all gun sales and transfers of ownership." },
    { season: "2017-18", when: "September/October", text: "Resolved: Deployment of anti-missile systems is in South Korea's best interest." },
    { season: "2016-17", when: "Nationals", text: "Resolved: In East Africa, the United States federal government should prioritize its counterterrorism efforts over its humanitarian assistance." },
    { season: "2016-17", when: "April", text: "Resolved: The United States ought to replace the Electoral College with a direct national popular vote." },
    { season: "2016-17", when: "March", text: "Resolved: The United States should no longer pressure Israel to work toward a two-state solution." },
    { season: "2016-17", when: "February", text: "Resolved: The United States should lift its embargo against Cuba." },
    { season: "2016-17", when: "January", text: "Resolved: In order to better respond to international conflicts, the United States should significantly increase its military spending." },
    { season: "2016-17", when: "December", text: "Resolved: The United States should end Plan Colombia." },
    { season: "2016-17", when: "November", text: "Resolved: On balance, the benefits of the Internet of Things outweigh the harms of decreased personal privacy." },
    { season: "2016-17", when: "September/October", text: "Resolved: In United States public K-12 schools, the probable cause standard ought to apply to searches of students." },
    { season: "2015-16", when: "Nationals", text: "Resolved: On balance, a one-day national primary would be more beneficial for the United States than our current presidential primary process." },
    { season: "2015-16", when: "April", text: "Resolved: To alleviate income inequality in the United States, increased spending on public infrastructure should be prioritized over increased spending on means-tested welfare programs." },
    { season: "2015-16", when: "March", text: "Resolved: The United States should withdraw its military presence from Okinawa." },
    { season: "2015-16", when: "February", text: "Resolved: The United States federal government should adopt a carbon tax." },
    { season: "2015-16", when: "January", text: "Resolved: On balance, economic sanctions are reducing the threat Russia poses to Western interests." },
    { season: "2015-16", when: "December", text: "Resolved: On balance, standardized testing is beneficial to K-12 education in the United States." },
    { season: "2015-16", when: "November", text: "Resolved: In response to the current crisis, a government should prioritize the humanitarian needs of refugees over its national interests." },
    { season: "2015-16", when: "September/October", text: "Resolved: The United States Federal Government ought to pay reparations to African Americans." },
    { season: "2014-15", when: "Nationals", text: "Resolved: The benefits of First Amendment protection of anonymous speech outweigh the harms." },
    { season: "2014-15", when: "April", text: "Resolved: Committing United States ground combat troops to fight ISIL is in the best interest of the United States." },
    { season: "2014-15", when: "March", text: "Resolved: In the United States, students should be guaranteed two years of free tuition to a community or technical college." },
    { season: "2014-15", when: "February", text: "Resolved: On balance, economic globalization benefits worldwide poverty reduction." },
    { season: "2014-15", when: "January", text: "Resolved: United Nations peacekeepers should have the power to engage in offensive operations." },
    { season: "2014-15", when: "December", text: "Resolved: For-profit prisons in the United States should be banned." },
    { season: "2014-15", when: "November", text: "Resolved: On balance, the benefits of genetically modified foods outweigh the harms." },
    { season: "2014-15", when: "September/October", text: "Resolved: On balance, public subsidies for professional athletic organizations in the United States benefit their local communities." },
    { season: "2013-14", when: "Nationals", text: "Resolved: NATO should strengthen its relationship with Ukraine in order to deter further Russian aggression." },
    { season: "2013-14", when: "April", text: "Resolved: Prioritizing economic development over environmental protection is in the best interest of the people of India." },
    { season: "2013-14", when: "March", text: "Resolved: Single-gender classrooms would improve the quality of education in American public schools." },
    { season: "2013-14", when: "February", text: "Resolved: The Supreme Court rightly decided that Section 4 of the Voting Rights Act violated the Constitution." },
    { season: "2013-14", when: "January", text: "Resolved: Development assistance should be prioritized over military aid in the Sahel region of Africa." },
    { season: "2013-14", when: "December", text: "Resolved: Immigration reform should include a path to citizenship for undocumented immigrants currently living in the United States." },
    { season: "2013-14", when: "November", text: "Resolved: The benefits of domestic surveillance by the National Security Agency outweigh the harms." },
    { season: "2013-14", when: "September/October", text: "Resolved: Unilateral military force by the United States is justified to prevent nuclear proliferation." },
    { season: "2012-13", when: "Nationals", text: "Resolved: The benefits of American drone strikes against foreign targets outweigh the harms." },
    { season: "2012-13", when: "April", text: "Resolved: The continuation of current U.S. anti-drug policies in Latin America will do more harm than good." },
    { season: "2012-13", when: "March", text: "Resolved: The U.S. government should not require its citizens to have health insurance." },
    { season: "2012-13", when: "February", text: "Resolved: On balance, the rise of China is beneficial to the interests of the United States." },
    { season: "2012-13", when: "January", text: "Resolved: On balance, the Supreme Court decision in Citizens United v. Federal Election Commission harms the election process." },
    { season: "2012-13", when: "December", text: "Resolved: The United States should prioritize tax increases over spending cuts." },
    { season: "2012-13", when: "November", text: "Resolved: Current U.S. foreign policy in the Middle East undermines our national security." },
    { season: "2012-13", when: "October", text: "Resolved: Developed countries have a moral obligation to mitigate the effects of climate change." },
    { season: "2012-13", when: "September", text: "Resolved: Congress should renew the Federal Assault Weapons Ban." },
    { season: "2011-12", when: "Nationals", text: "Resolved: Stand Your Ground laws are a legitimate expansion of the doctrine of self defense." },
    { season: "2011-12", when: "April", text: "Resolved: State mandated administration of childhood vaccinations is justified." },
    { season: "2011-12", when: "March", text: "Resolved: The United States should suspend all assistance to Pakistan." },
    { season: "2011-12", when: "February", text: "Resolved: Birthright citizenship should be abolished in the United States." },
    { season: "2011-12", when: "January", text: "Resolved: The costs of a college education outweigh the benefits." },
    { season: "2011-12", when: "December", text: "Resolved: In the United States, current income disparities threaten democratic ideals." },
    { season: "2011-12", when: "November", text: "Resolved: Direct popular vote should replace electoral vote in presidential elections." },
    { season: "2011-12", when: "October", text: "Resolved: Private sector investment in human space exploration is preferable to public sector investment." },
    { season: "2011-12", when: "September", text: "Resolved: The benefits of post-9/11 security measures outweigh the harms to personal freedom." },
    { season: "2010-11", when: "Nationals", text: "Resolved: That the United States should intervene in another nation's struggle for democracy." },
    { season: "2010-11", when: "April", text: "Resolved: The United States federal government should permit the use of financial incentives to encourage organ donation." },
    { season: "2010-11", when: "March", text: "Resolved: North Korea poses a more serious threat to United States national security than Iran." },
    { season: "2010-11", when: "February", text: "Resolved: Wikileaks is a threat to United States national security." },
    { season: "2010-11", when: "January", text: "Resolved: In the United States, plea bargaining undermines the criminal justice system." },
    { season: "2010-11", when: "December", text: "Resolved: Cyberbullying should be a criminal offense." },
    { season: "2010-11", when: "November", text: "Resolved: High school Public Forum Debate resolutions should not confront sensitive religious issues." },
    { season: "2010-11", when: "October", text: "Resolved: NATO presence improves the lives of Afghan citizens." },
    { season: "2010-11", when: "September", text: "Resolved: Allowing deep water offshore oil drilling is in the best interest of the United States." },
    { season: "2009-10", when: "Nationals", text: "Resolved: Current trends in American political dialogue compromise meaningful democratic deliberation." },
    { season: "2009-10", when: "April", text: "Resolved: On balance, government employee labor unions have a positive impact on the United States." },
    { season: "2009-10", when: "March", text: "Resolved: Affirmative action to promote equal opportunity in the United States is justified." },
    { season: "2009-10", when: "February", text: "Resolved: In the United States, organized political lobbying does more harm than good." },
    { season: "2009-10", when: "January", text: "Resolved: President Obama's plan for increasing troops in Afghanistan is in the United States' best interest." },
    { season: "2009-10", when: "December", text: "Resolved: That merit pay based on student achievement should be a significant component of K-12 teacher compensation in United States public schools." },
    { season: "2009-10", when: "November", text: "Resolved: Failed nations are a greater threat to the United States than stable nations." },
    { season: "2009-10", when: "October", text: "Resolved: When in conflict, the United Nations should prioritize global poverty reduction over environmental protection." },
    { season: "2009-10", when: "September", text: "Resolved: United States policy on illegal immigration should focus on attrition through enforcement rather than amnesty." },
    { season: "2008-09", when: "Nationals", text: "Resolved: That the United States should normalize relations with Cuba." },
    { season: "2008-09", when: "April", text: "Resolved: That the Employee Free Choice Act of 2009 serves the best interest of the American people." },
    { season: "2008-09", when: "March", text: "Resolved: That, on balance, the No Child Left Behind Act of 2001 has improved academic achievement in the United States." },
    { season: "2008-09", when: "February", text: "Resolved: That, on balance, the rise of Brazil, Russia, India, and China (BRIC) has had a positive impact on the United States." },
    { season: "2008-09", when: "January", text: "Resolved: That, by 2040, the federal government should mandate that all new passenger vehicles and light trucks sold in the United States be powered by alternative fuels." },
    { season: "2008-09", when: "December", text: "Resolved: That, on balance, social networking Web sites have a positive impact on the United States." },
    { season: "2008-09", when: "November", text: "Resolved: That the United States government should implement universal health care modeled after the French system." },
    { season: "2008-09", when: "October", text: "Resolved: The United States should significantly increase its use of nuclear energy." },
    { season: "2008-09", when: "September", text: "Resolved: That the United States should implement a military draft." },
    { season: "2007-08", when: "Nationals", text: "Resolved: US policies established after September 11, 2001 have substantially reduced the risk of terrorist acts against the United States." },
    { season: "2007-08", when: "April", text: "Resolved: That the Economic Stimulus Act of 2008 will successfully mitigate economic slowdowns over the next year." },
    { season: "2007-08", when: "March", text: "Resolved: The US system of presidential primaries is contrary to democratic values." },
    { season: "2007-08", when: "February", text: "Resolved: That Russia has become a threat to U.S. interests." },
    { season: "2007-08", when: "January", text: "Resolved: In a democracy, civil disobedience is an appropriate weapon in the fight for justice." },
    { season: "2007-08", when: "December", text: "Resolved: That the United States would be justified in pursuing military options against Iran." },
    { season: "2007-08", when: "November", text: "Resolved: That eliminating United States government budget deficits should be prioritized over increasing domestic spending." },
    { season: "2007-08", when: "October", text: "Resolved: That the United States should encourage the implementation of a soft partition of Iraq." },
    { season: "2007-08", when: "September", text: "Resolved: That the Fairness Doctrine should be reinstated." },
    { season: "2006-07", when: "Nationals", text: "Resolved: That the private ownership of handguns should be banned in the United States." },
    { season: "2006-07", when: "April", text: "Resolved: United States corporations should honor all prior commitments to employee pensions." },
    { season: "2006-07", when: "March", text: "Resolved: That the quantity of credit available to American consumers should be significantly reduced." },
    { season: "2006-07", when: "February", text: "Resolved: The costs of legalized casino gambling in the United States outweigh the benefits." },
    { season: "2006-07", when: "January", text: "Resolved: That lobbyists negatively influence the legislative process in the United States." },
    { season: "2006-07", when: "December", text: "Resolved: Colleges and Universities in the United States should end their early admission programs." },
    { season: "2006-07", when: "November", text: "Resolved: That participating in multinational diplomatic efforts is beneficial to U.S. interests." },
    { season: "2006-07", when: "October", text: "Resolved: Current immigration laws in the United States should be enforced." },
    { season: "2006-07", when: "September", text: "Resolved: That the benefits of NASA's space exploration programs justify the costs." },
    { season: "2005-06", when: "Nationals", text: "Resolved: That the United States government should ratify the Kyoto Protocol." },
    { season: "2005-06", when: "April", text: "Resolved: That the American media work against the best interest of the American public." },
    { season: "2005-06", when: "March", text: "Resolved: That big box retailers benefit the communities in which they are located." },
    { season: "2005-06", when: "February", text: "Resolved: That the policy decisions of the current Israeli government toward the Palestinian state have improved prospects for peace in the Middle East." },
    { season: "2005-06", when: "January", text: "Resolved: In the United States, public high school science curriculum should include the study of the Theory of Intelligent Design." },
    { season: "2005-06", when: "December", text: "Resolved: That the National Basketball Association (NBA) should rescind its dress code." },
    { season: "2005-06", when: "November", text: "Resolved: That the United States federal government should fund Hurricane Katrina relief and rebuilding by ending President Bush's tax cuts." },
    { season: "2005-06", when: "October", text: "Resolved: That the United Nations should be the primary agent to lead and direct the fight against terrorism around the world." },
    { season: "2005-06", when: "September", text: "Resolved: In the United States, colleges and universities should be permitted to pay stipends to their Division I athletes." },
    { season: "2004-05", when: "Nationals", text: "Resolved: That, when a choice is required for public high schools in the United States, government funding should prioritize vocational education over college preparatory education." },
    { season: "2004-05", when: "April", text: "Resolved: The United States should issue guest worker visas to illegal aliens." },
    { season: "2004-05", when: "March", text: "Resolved: Student aptitude should be assessed through standardized testing." },
    { season: "2004-05", when: "February", text: "Resolved: In the United States, the current system of federal income taxation should be replaced by a flat rate income tax." },
    { season: "2004-05", when: "January", text: "Resolved: The United States Constitution should be amended to establish a mandatory retirement age for Supreme Court Justices." },
    { season: "2004-05", when: "December", text: "Resolved: Corporate offshoring aids in the economic development of the United States." },
    { season: "2004-05", when: "November", text: "Resolved: The United States government should allow Americans to purchase prescription drugs from other countries." },
    { season: "2004-05", when: "October", text: "Resolved: In the United States, public opinion polls positively affect the election process." },
    { season: "2004-05", when: "September", text: "Resolved: That the United States should establish a cabinet-level position to oversee its entire intelligence community." },
    { season: "2003-04", when: "Nationals", text: "Resolved: All young adults in every nation should be required to perform at least one full year of national service." },
    { season: "2003-04", when: "April", text: "Resolved: English should be the official national language of the United States." },
    { season: "2003-04", when: "March", text: "Resolved: The United States should provide universal health care insurance to all U.S. citizens." },
    { season: "2003-04", when: "February", text: "Resolved: Americans should be allowed to share copyrighted media over the internet." },
    { season: "2003-04", when: "January", text: "Resolved: The United States is losing the War on Terror." },
    { season: "2003-04", when: "December", text: "Resolved: Congress should repeal the No Child Left Behind Act." },
    { season: "2003-04", when: "November", text: "Resolved: That Federal judges should be elected in their district for a limited term rather than appointed by the President for a life term." },
    { season: "2003-04", when: "October", text: "Resolved: That the United States should comply with United Nations' decisions concerning international peacekeeping operations." },
    { season: "2003-04", when: "September", text: "Resolved: Use of a cell phone should be prohibited while operating a motor vehicle." },
    { season: "2002-03", when: "Nationals", text: "Resolved: That the United States should assume primary responsibility for the rebuilding of Iraq." },
    { season: "2002-03", when: "April", text: "Resolved: Awards for pain and suffering in medical malpractice cases should be limited to $250,000." },
    { season: "2002-03", when: "March", text: "Resolved: Affirmative action should not be practiced in college and university admission." },
    { season: "2002-03", when: "February", text: "Resolved: The death penalty should be abolished in America." },
    { season: "2002-03", when: "January", text: "Resolved: The Federal Government should authorize oil exploration in the Arctic National Wildlife Reserve." },
    { season: "2002-03", when: "December", text: "Resolved: The \"Bush\" tax cuts should be made permanent." },
    { season: "2002-03", when: "October/November", text: "Resolved: Commercial airline pilots should be armed in the cockpit." },
  ],
  "Lincoln-Douglas": [
    { season: "2025-26", when: "Nationals", text: "Resolved: Democracies ought to prioritize the protection of civil liberties over national security." },
    { season: "2025-26", when: "March/April", text: "Resolved: The United States military ought to abide by the principle of non-intervention." },
    { season: "2025-26", when: "January/February", text: "Resolved: The possession of nuclear weapons is immoral." },
    { season: "2025-26", when: "November/December", text: "Resolved: The United States ought to rewild substantial tracts of land." },
    { season: "2025-26", when: "September/October", text: "Resolved: In the United States criminal justice system, plea bargaining is just." },
    { season: "2024-25", when: "Nationals", text: "Resolved: Violent revolution is a just response to political oppression." },
    { season: "2024-25", when: "March/April", text: "Resolved: The development of Artificial General Intelligence is immoral." },
    { season: "2024-25", when: "January/February", text: "Resolved: The United States ought to become party to the United Nations Convention on the Law of the Sea and/or the Rome Statute of the International Criminal Court." },
    { season: "2024-25", when: "November/December", text: "Resolved: The United States ought to adopt a wealth tax." },
    { season: "2024-25", when: "September/October", text: "Resolved: The United States ought to require that workers receive a living wage." },
    { season: "2023-24", when: "Nationals", text: "Resolved: In a democracy, a people ought to have the right to secede from their government." },
    { season: "2023-24", when: "March/April", text: "Resolved: The primary objective of the United States criminal justice system ought to be rehabilitation." },
    { season: "2023-24", when: "January/February", text: "Resolved: The United States ought to substantially reduce its military presence in the West Asia-North Africa region." },
    { season: "2023-24", when: "November/December", text: "Resolved: The United States ought to prohibit the extraction of fossil fuels from federal public lands and waters." },
    { season: "2023-24", when: "September/October", text: "Resolved: The United States ought to guarantee the right to housing." },
    { season: "2022-23", when: "Nationals", text: "Resolved: Government employees have a moral obligation to leak classified information to address injustice." },
    { season: "2022-23", when: "March/April", text: "Resolved: The justices of the Supreme Court of the United States ought to be term-limited." },
    { season: "2022-23", when: "January/February", text: "Resolved: Justice requires open borders for human migration." },
    { season: "2022-23", when: "November/December", text: "Resolved: The People's Republic of China ought to prioritize environmental protection over economic growth." },
    { season: "2022-23", when: "September/October", text: "Resolved: The United States ought to implement a single-payer universal healthcare system." },
    { season: "2021-22", when: "Nationals", text: "Resolved: Radicalism is preferable to incrementalism to achieve social justice." },
    { season: "2021-22", when: "March/April", text: "Resolved: In a democracy, a free press ought to prioritize objectivity over advocacy." },
    { season: "2021-22", when: "January/February", text: "Resolved: The appropriation of outer space by private entities is unjust." },
    { season: "2021-22", when: "November/December", text: "Resolved: A just government ought to recognize an unconditional right of workers to strike." },
    { season: "2021-22", when: "September/October", text: "Resolved: The member nations of the World Trade Organization ought to reduce intellectual property protections for medicines." },
    { season: "2020-21", when: "Nationals", text: "Resolved: A public health emergency justifies limiting civil liberties." },
    { season: "2020-21", when: "March/April", text: "Resolved: The United States ought to guarantee universal child care." },
    { season: "2020-21", when: "January/February", text: "Resolved: States ought to ban lethal autonomous weapons." },
    { season: "2020-21", when: "November/December", text: "Resolved: The United States ought to provide a federal jobs guarantee." },
    { season: "2020-21", when: "September/October", text: "Resolved: In a democracy, voting ought to be compulsory." },
    { season: "2019-20", when: "Nationals", text: "Resolved: The intergenerational accumulation of wealth is antithetical to democracy." },
    { season: "2019-20", when: "March/April", text: "Resolved: Predictive policing is unjust." },
    { season: "2019-20", when: "January/February", text: "Resolved: States ought to eliminate their nuclear arsenals." },
    { season: "2019-20", when: "November/December", text: "Resolved: The United States ought to eliminate subsidies for fossil fuels." },
    { season: "2019-20", when: "September/October", text: "Resolved: In the United States, colleges and universities ought not consider standardized tests in undergraduate admissions decisions." },
    { season: "2018-19", when: "Nationals", text: "Resolved: Violent revolution is a just response to political oppression." },
    { season: "2018-19", when: "March/April", text: "Resolved: The illegal use of drugs ought to be treated as a matter of public health, not of criminal justice." },
    { season: "2018-19", when: "January/February", text: "Resolved: The United States ought not provide military aid to authoritarian regimes." },
    { season: "2018-19", when: "November/December", text: "Resolved: In a democracy, the public's right to know ought to be valued above the right to privacy of candidates for public office." },
    { season: "2018-19", when: "September/October", text: "Resolved: In the United States, reporters ought to have the right to protect the identity of confidential sources." },
    { season: "2017-18", when: "Nationals", text: "Resolved: The United States' use of targeted killing in foreign countries is unjust." },
    { season: "2017-18", when: "March/April", text: "Resolved: The United States ought to provide a universal basic income." },
    { season: "2017-18", when: "January/February", text: "Resolved: Plea bargaining ought to be abolished in the United States criminal justice system." },
    { season: "2017-18", when: "November/December", text: "Resolved: Wealthy nations have an obligation to provide development assistance to other nations." },
    { season: "2017-18", when: "September/October", text: "Resolved: In the United States, national service ought to be compulsory." },
    { season: "2016-17", when: "Nationals", text: "Resolved: A just government ought to prioritize civil liberties over national security." },
    { season: "2016-17", when: "March/April", text: "Resolved: The United States ought to guarantee the right to housing." },
    { season: "2016-17", when: "January/February", text: "Resolved: Public colleges and universities in the United States ought not restrict any constitutionally protected speech." },
    { season: "2016-17", when: "November/December", text: "Resolved: The United States ought to limit qualified immunity for police officers." },
    { season: "2016-17", when: "September/October", text: "Resolved: Countries ought to prohibit the production of nuclear power." },
    { season: "2015-16", when: "Nationals", text: "Resolved: Immigration ought to be recognized as a human right." },
    { season: "2015-16", when: "March/April", text: "Resolved: The United States ought to promote democracy in the Middle East." },
    { season: "2015-16", when: "January/February", text: "Resolved: In the United States, private ownership of handguns ought to be banned." },
    { season: "2015-16", when: "November/December", text: "Resolved: In the United States criminal justice system, jury nullification ought to be used in the face of perceived injustice." },
    { season: "2015-16", when: "September/October", text: "Resolved: Adolescents ought to have the right to make autonomous medical choices." },
    { season: "2014-15", when: "Nationals", text: "Resolved: Inaction in the face of injustice makes individuals morally culpable." },
    { season: "2014-15", when: "March/April", text: "Resolved: Just governments ought to ensure food security for their citizens." },
    { season: "2014-15", when: "January/February", text: "Resolved: Just governments ought to require that employers pay a living wage." },
    { season: "2014-15", when: "November/December", text: "Resolved: The \"right to be forgotten\" from Internet searches ought to be a civil right." },
    { season: "2014-15", when: "September/October", text: "Resolved: A just society ought to presume consent for organ procurement from the deceased." },
    { season: "2013-14", when: "Nationals", text: "Resolved: The United States ought to prioritize the pursuit of national security objectives above the digital privacy of its citizens." },
    { season: "2013-14", when: "March/April", text: "Resolved: Placing political conditions on humanitarian aid to foreign countries is unjust." },
    { season: "2013-14", when: "January/February", text: "Resolved: Developing countries should prioritize environmental protection over resource extraction when the two are in conflict." },
    { season: "2013-14", when: "November/December", text: "Resolved: In the United States criminal justice system, truth-seeking ought to take precedence over attorney-client privilege." },
    { season: "2013-14", when: "September/October", text: "Resolved: In a democracy, voting ought to be compulsory." },
    { season: "2012-13", when: "Nationals", text: "Resolved: Oppressive government is more desirable than no government." },
    { season: "2012-13", when: "March/April", text: "Resolved: The United States is justified in intervening in the internal political processes of other countries to attempt to stop human rights abuses." },
    { season: "2012-13", when: "January/February", text: "Resolved: Rehabilitation ought to be valued above retribution in the United States criminal justice system." },
    { season: "2012-13", when: "November/December", text: "Resolved: The United States ought to guarantee universal health care for its citizens." },
    { season: "2012-13", when: "September/October", text: "Resolved: The United States ought to extend to non-citizens accused of terrorism the same constitutional due process protections it grants to citizens." },
    { season: "2011-12", when: "Nationals", text: "Resolved: A government has the obligation to lessen the economic gap between its rich and poor citizens." },
    { season: "2011-12", when: "March/April", text: "Resolved: Targeted killing is a morally permissible foreign policy tool." },
    { season: "2011-12", when: "January/February", text: "Resolved: It is morally permissible for victims to use deadly force as a deliberate response to repeated domestic violence." },
    { season: "2011-12", when: "November/December", text: "Resolved: Individuals have a moral obligation to assist people in need." },
    { season: "2011-12", when: "September/October", text: "Resolved: Justice requires the recognition of animal rights." },
    { season: "2010-11", when: "Nationals", text: "Resolved: When forced to choose, a just government ought to prioritize universal human rights over its national interest." },
    { season: "2010-11", when: "March/April", text: "Resolved: The United States is justified in using private military firms abroad to pursue its military objectives." },
    { season: "2010-11", when: "January/February", text: "Resolved: In the United States, juveniles charged with violent felonies ought to be treated as adults in the criminal justice system." },
    { season: "2010-11", when: "November/December", text: "Resolved: The abuse of illegal drugs ought to be treated as a matter of public health, not of criminal justice." },
    { season: "2010-11", when: "September/October", text: "Resolved: States ought not possess nuclear weapons." },
    { season: "2009-10", when: "Nationals", text: "Resolved: Compulsory inclusion of non-felons' DNA in any government database is unjust." },
    { season: "2009-10", when: "March/April", text: "Resolved: In the United States, the principle of jury nullification is a just check on government." },
    { season: "2009-10", when: "January/February", text: "Resolved: Economic sanctions ought not be used to achieve foreign policy objectives." },
    { season: "2009-10", when: "November/December", text: "Resolved: Public health concerns justify compulsory immunization." },
    { season: "2009-10", when: "September/October", text: "Resolved: Public high school students in the United States ought not be required to pass standardized exit exams to graduate." },
    { season: "2008-09", when: "Nationals", text: "Resolved: Military conscription is unjust." },
    { season: "2008-09", when: "March/April", text: "Resolved: Vigilantism is justified when the government has failed to enforce the law." },
    { season: "2008-09", when: "January/February", text: "Resolved: The United States ought to submit to the jurisdiction of an international court designed to prosecute crimes against humanity." },
    { season: "2008-09", when: "November/December", text: "Resolved: In a democratic society, felons ought to retain the right to vote." },
    { season: "2008-09", when: "September/October", text: "Resolved: It is morally permissible to kill one innocent person to save the lives of more innocent people." },
    { season: "2007-08", when: "Nationals", text: "Resolved: Limiting economic inequality ought to be a more important social goal than maximizing economic freedom." },
    { season: "2007-08", when: "March/April", text: "Resolved: Hate crime enhancements are unjust in the United States." },
    { season: "2007-08", when: "January/February", text: "Resolved: It is just for the United States to use military force to prevent the acquisition of nuclear weapons by nations that pose a military threat." },
    { season: "2007-08", when: "November/December", text: "Resolved: In the United States, plea-bargaining in exchange for testimony is unjust." },
    { season: "2007-08", when: "September/October", text: "Resolved: A just society ought not use the death penalty as a form of punishment." },
    { season: "2006-07", when: "Nationals", text: "Resolved: On balance, violent revolution is a just response to political oppression." },
    { season: "2006-07", when: "March/April", text: "Resolved: The United Nations' obligation to protect global human rights ought to be valued above its obligation to respect national sovereignty." },
    { season: "2006-07", when: "January/February", text: "Resolved: The actions of corporations ought to be held to the same moral standards as the actions of individuals." },
    { season: "2006-07", when: "November/December", text: "Resolved: A victim's deliberate use of deadly force is a just response to repeated domestic violence." },
    { season: "2006-07", when: "September/October", text: "Resolved: A just government should provide health care to its citizens." },
    { season: "2005-06", when: "Nationals", text: "Resolved: In matters of collecting military intelligence, the ends justify the means." },
    { season: "2005-06", when: "March/April", text: "Resolved: Juveniles charged with violent crimes should be tried and punished as adults." },
    { season: "2005-06", when: "January/February", text: "Resolved: The use of the state's power of eminent domain to promote private enterprise is unjust." },
    { season: "2005-06", when: "November/December", text: "Resolved: Judicial activism is necessary to protect the rights of American citizens." },
    { season: "2005-06", when: "September/October", text: "Resolved: In matters of U.S. immigration policy, restrictions on the rights of non-citizens are consistent with democratic ideals." },
    { season: "2004-05", when: "Nationals", text: "Resolved: The pursuit of scientific knowledge ought to be constrained by concern for societal good." },
    { season: "2004-05", when: "March/April", text: "Resolved: To better protect civil liberties, community standards ought to take precedence over conflicting national standards." },
    { season: "2004-05", when: "January/February", text: "Resolved: Democracy is best served by strict separation of church and state." },
    { season: "2004-05", when: "November/December", text: "Resolved: The United States has a moral obligation to promote democratic ideals in other nations." },
    { season: "2004-05", when: "September/October", text: "Resolved: Individual claims of privacy ought to be valued above competing claims of societal welfare." },
    { season: "2003-04", when: "Nationals", text: "Resolved: Civil disobedience in a democracy is morally justified." },
    { season: "2003-04", when: "March/April", text: "Resolved: As a general principle, individuals have an obligation to value the common good above their own interests." },
    { season: "2003-04", when: "January/February", text: "Resolved: A government's obligation to protect the environment ought to take precedence over its obligation to promote economic development." },
    { season: "2003-04", when: "November/December", text: "Resolved: The United States has a moral obligation to mitigate international conflicts." },
    { season: "2003-04", when: "September/October", text: "Resolved: In the U.S. judicial system, truth seeking ought to take precedence over privileged communication." },
    { season: "2002-03", when: "Nationals", text: "Resolved: Rehabilitation ought to be valued above punishment in the U.S. criminal justice system." },
    { season: "2002-03", when: "March/April", text: "Resolved: When in conflict, the letter of the law ought to take priority over the spirit of the law." },
    { season: "2002-03", when: "January/February", text: "Resolved: When in conflict, globalization ought to be valued above national sovereignty." },
    { season: "2002-03", when: "November/December", text: "Resolved: When in conflict, academic freedom in U.S. high schools ought to be valued above community standards." },
    { season: "2002-03", when: "September/October", text: "Resolved: When the United States is engaged in military conflict, the demands of national security ought to supersede conflicting claims of individual rights." },
    { season: "2001-02", when: "Nationals", text: "Resolved: Laws which protect citizens from themselves are justified." },
    { season: "2001-02", when: "March/April", text: "Resolved: Limiting the freedom of expression of adults is justified by society's interest in protecting children." },
    { season: "2001-02", when: "January/February", text: "Resolved: Oppressive government is more desirable than no government." },
    { season: "2001-02", when: "November/December", text: "Resolved: A lesser developed nation's right to develop ought to take priority over its obligation to protect the environment." },
    { season: "2001-02", when: "September/October", text: "Resolved: Decentralized governmental power ought to be a fundamental goal of democratic society." },
    { season: "2000-01", when: "Nationals", text: "Resolved: On balance, violent revolution is a just response to oppression." },
    { season: "2000-01", when: "March/April", text: "Resolved: The public's right to know ought to be valued above the right to privacy of candidates for public office." },
    { season: "2000-01", when: "January/February", text: "Resolved: The possession of nuclear weapons is immoral." },
    { season: "2000-01", when: "November/December", text: "Resolved: Establishing a safe educational environment in grades K-12 justifies infringement of students' civil liberties." },
    { season: "2000-01", when: "September/October", text: "Resolved: Colleges and universities have a moral obligation to prohibit the public expression of hate speech on their campuses." },
    { season: "1999-2000", when: "Nationals", text: "Resolved: Inaction in the face of injustice makes an individual morally culpable." },
    { season: "1999-2000", when: "March/April", text: "Resolved: The intervention of one nation in the domestic affairs of another nation is morally justified." },
    { season: "1999-2000", when: "January/February", text: "Resolved: Violent juvenile offenders ought to be treated as adults in the criminal justice system." },
    { season: "1999-2000", when: "November/December", text: "Resolved: The use of economic sanctions to achieve U.S. foreign policy goals is moral." },
    { season: "1999-2000", when: "September/October", text: "Resolved: When they conflict, respect for cultural sensitivity ought to be valued above the commercial use of free speech." },
    { season: "1998-99", when: "Nationals", text: "Resolved: Capitalism is superior to socialism as a means of achieving economic justice." },
    { season: "1998-99", when: "March/April", text: "Resolved: Human genetic engineering is morally justified." },
    { season: "1998-99", when: "January/February", text: "Resolved: In the United States, a journalist's right to shield confidential sources ought to be protected by the First Amendment." },
    { season: "1998-99", when: "November/December", text: "Resolved: Capital punishment is justified." },
    { season: "1998-99", when: "September/October", text: "Resolved: The individual ought to value the sanctity of life above the quality of life." },
    { season: "1997-98", when: "Nationals", text: "Resolved: In the United States' justice system, due process ought to be valued above the pursuit of truth when they are in conflict." },
    { season: "1997-98", when: "March/April", text: "Resolved: Civil disobedience is justified in a democracy." },
    { season: "1997-98", when: "January/February", text: "Resolved: A just social order ought to place the principle of equality above that of liberty." },
    { season: "1997-98", when: "November/December", text: "Resolved: An adolescent's right to privacy ought to be valued above a parent's conflicting right to know." },
    { season: "1997-98", when: "September/October", text: "Resolved: Global concerns ought to be valued above conflicting national concerns." },
    { season: "1996-97", when: "Nationals", text: "Resolved: The public's right to know is of greater value than the individual's right to privacy." },
    { season: "1996-97", when: "March/April", text: "Resolved: On balance, individuals ought to have a greater obligation to themselves than to their community." },
    { season: "1996-97", when: "January/February", text: "Resolved: In United States policy, the principle of universal human rights ought to take precedence over conflicting national interest." },
    { season: "1996-97", when: "November/December", text: "Resolved: When they are in conflict, a business' responsibility to itself ought to be valued above its responsibility to society." },
    { season: "1996-97", when: "September/October", text: "Resolved: When in conflict, society's goal of eliminating discrimination ought to transcend an individual's right to participate in exclusive, voluntary associations." },
    { season: "1995-96", when: "Nationals", text: "Resolved: That limiting constitutional freedoms is a just response to terrorism in the United States." },
    { season: "1995-96", when: "March/April", text: "Resolved: When in conflict, American cultural unity ought to be valued above cultural diversity." },
    { season: "1995-96", when: "January/February", text: "Resolved: An oppressive government is more desirable than no government." },
    { season: "1995-96", when: "November/December", text: "Resolved: The pursuit of feminist ideals is detrimental to the achievement of gender equality." },
    { season: "1995-96", when: "September/October", text: "Resolved: Individuals with disabilities ought to be afforded the same athletic competition opportunities as able-bodied athletes." },
    { season: "1994-95", when: "Nationals", text: "Resolved: When in conflict, the safety of others is of greater value than the right to privacy of those with infectious diseases." },
    { season: "1994-95", when: "March/April", text: "Resolved: On balance, institutional censorship of academic material is harmful to the educational development of students." },
    { season: "1994-95", when: "January/February", text: "Resolved: Laws which protect citizens from themselves are justified." },
    { season: "1994-95", when: "November/December", text: "Resolved: When in conflict, community standards are of greater value than individual liberty." },
    { season: "1994-95", when: "September/October", text: "Resolved: An individual's freedom of expression is of greater value than political correctness." },
    { season: "1993-94", when: "Nationals", text: "Resolved: When in conflict, protection of the innocent is of greater value than prosecution of the guilty." },
    { season: "1993-94", when: "March/April", text: "Resolved: Terminally ill patients have the right to die when and how they choose." },
    { season: "1993-94", when: "January/February", text: "Resolved: When called upon by one's government, individuals are morally obligated to risk their lives for their country." },
    { season: "1993-94", when: "November/December", text: "Resolved: The public's right to know is of greater value than the right to privacy of candidates for public office." },
    { season: "1993-94", when: "September/October", text: "Resolved: Secondary education in the United States ought to be a privilege, not a right." },
    { season: "1992-93", when: "Nationals", text: "Resolved: The protection of domestic order justifies the curtailment of First Amendment rights." },
    { season: "1992-93", when: "March/April", text: "Resolved: The principle of majority rule ought to be valued above the principle of minority rights." },
    { season: "1992-93", when: "January/February", text: "Resolved: When in conflict, the spirit of the law ought to take priority over the letter of the law." },
    { season: "1992-93", when: "November/December", text: "Resolved: In the criminal justice system, truth seeking ought to take precedence over privileged communication." },
    { season: "1992-93", when: "September/October", text: "Resolved: U.S. military interference in the internal affairs of other countries is justified." },
    { season: "1991-92", when: "Nationals", text: "Resolved: The United States government ought to provide for the medical care of its citizens." },
    { season: "1991-92", when: "March/April", text: "Resolved: The possession of nuclear weapons is immoral." },
    { season: "1991-92", when: "January/February", text: "Resolved: A victim's deliberate use of deadly force is justified as a response to physical abuse." },
    { season: "1991-92", when: "November/December", text: "Resolved: Human genetic engineering is morally justified." },
    { season: "1991-92", when: "September/October", text: "Resolved: A liberal arts curriculum is preferable to an employment-readiness curriculum in U.S. secondary schools." },
    { season: "1990-91", when: "Nationals", text: "Resolved: Members of the United States Congress ought to value the national interest above constituents' interests when the two are in conflict." },
    { season: "1990-91", when: "March/April", text: "Resolved: The pursuit of scientific knowledge ought to be limited by a concern for societal good." },
    { season: "1990-91", when: "January/February", text: "Resolved: Showing disrespect for the American flag is antithetical to fundamental American values." },
    { season: "1990-91", when: "November/December", text: "Resolved: Government limits on the individual's right to bear arms in the United States are justified." },
    { season: "1990-91", when: "September/October", text: "Resolved: Competition is superior to cooperation as a means of achieving excellence." },
    { season: "1989-90", when: "Nationals", text: "Resolved: Individual obedience to law plays a greater role in maintaining ethical public service than does individual obedience to conscience." },
    { season: "1989-90", when: "March/April", text: "Resolved: Development of natural resources ought to be valued above protection of the environment." },
    { season: "1989-90", when: "January/February", text: "Resolved: Communities in the United States ought to have the right to suppress pornography." },
    { season: "1989-90", when: "November/December", text: "Resolved: All United States citizens ought to perform a period of national service." },
    { season: "1989-90", when: "September/October", text: "Resolved: The United States ought to value global concerns above its own national concerns." },
    { season: "1988-89", when: "Nationals", text: "Resolved: The American criminal justice system ought to place a higher priority on retribution than on rehabilitation." },
    { season: "1988-89", when: "March/April", text: "Resolved: The public's right to know ought to be valued above U.S. national security interests." },
    { season: "1988-89", when: "January/February", text: "Resolved: Limitations upon the content of student publications by secondary school administrators are justified." },
    { season: "1988-89", when: "November/December", text: "Resolved: Affirmative action programs to remedy the effects of discrimination are justified." },
    { season: "1988-89", when: "September/October", text: "Resolved: The individual ought to value the sanctity of life above the quality of life." },
    { season: "1987-88", when: "Nationals", text: "Resolved: Violent revolution is a just response to oppression." },
    { season: "1987-88", when: "March/April/May", text: "Resolved: When they are in conflict, the principle of privileged communication ought to be subordinate to the maintenance of law and order." },
    { season: "1987-88", when: "December/January/February", text: "Resolved: The protection of society's health interests through broad based mandatory testing for AIDS ought to be more important than personal privacy rights." },
    { season: "1987-88", when: "September/October/November", text: "Resolved: The protection of public safety justifies random, mandatory drug testing throughout society." },
    { season: "1986-87", when: "Nationals", text: "Resolved: When they are in conflict, the right to a free press is a higher priority than the right to a fair trial." },
    { season: "1986-87", when: "March/April", text: "Resolved: A parliamentary system of government would better fulfill the values underlying the American Constitution." },
    { season: "1986-87", when: "January/February", text: "Resolved: Decisions of the U.S. Supreme Court in criminal cases ought to reflect the values of the American people." },
    { season: "1986-87", when: "November/December", text: "Resolved: An unjust government is better than no government at all." },
    { season: "1985-86", when: "Nationals", text: "Resolved: Giving sanctuary to illegal refugees in the United States justifiably places moral law above positive law." },
    { season: "1985-86", when: "March/April", text: "Resolved: Allowing innocent people to be harmed is preferable rather than giving into terrorists' demands." },
    { season: "1985-86", when: "January/February", text: "Resolved: The restriction of civil liberties in the United States for the sake of combating terrorism is justified." },
    { season: "1985-86", when: "November/December", text: "Resolved: The brotherhood of man transcends the sovereignty of nations." },
    { season: "1985-86", when: "September/October", text: "Resolved: The use of sanctions to achieve U.S. foreign policy goals ought to be immoral." },
    { season: "1984-85", when: "Nationals", text: "Resolved: The American media works against the best interest of the American public." },
    { season: "1984-85", when: "March/April", text: "Resolved: A just social order ought to place the principle of equality above that of liberty." },
    { season: "1984-85", when: "January/February", text: "Resolved: Nothing is politically right that is morally wrong." },
    { season: "1984-85", when: null, text: "Resolved: U.S. immigration policy is inconsistent with American ideals." },
    { season: "1983-84", when: "Nationals", text: "Resolved: Uniformity in education leads to mediocrity." },
    { season: "1983-84", when: "March/April", text: "Resolved: Civil disobedience is justified in a democracy." },
    { season: "1983-84", when: "January/February", text: "Resolved: Even in a democratic society morality can be legislated." },
    { season: "1982-83", when: "Nationals", text: "Resolved: Liberty is more precious than law." },
    { season: "1982-83", when: "March/April", text: "Resolved: Protection of the environment should take precedence over the development of natural resources." },
    { season: "1982-83", when: "January/February", text: "Resolved: Funding for human services programs should take precedence over a balanced budget." },
    { season: "1982-83", when: null, text: "Resolved: The right to die takes precedence over other ethical and moral considerations." },
    { season: "1982-83", when: null, text: "Resolved: The right to a free press outweighs the right to a fair trial." },
    { season: "1981-82", when: "Nationals", text: "Resolved: The economic health of a nation is more important than the social programs for its citizens." },
    { season: "1981-82", when: "March/April", text: "Resolved: It is undesirable to expend societal resources on the enforcement of laws against victimless crimes." },
    { season: "1981-82", when: "January/February", text: "Resolved: The rights of the victim should take precedence over the rights of the accused in felony cases." },
    { season: "1980-81", when: "Nationals", text: "Resolved: The protection of human rights should have a higher priority in shaping America's foreign policy." },
    { season: "1980-81", when: "March/April", text: "Resolved: Military conscription is a superior alternative to a voluntary army." },
    { season: "1980-81", when: "January/February", text: "Resolved: It is morally unjustifiable to require an individual to join a labor organization as a condition of employment." },
    { season: "1979-80", when: "Nationals", text: "Resolved: The strength of the present methods of funding the social security system outweighs the weaknesses." },
  ],
  Policy: [
    { season: "2025-26", when: null, text: "Resolved: The United States federal government should significantly increase its exploration and/or development of the Arctic." },
    { season: "2024-25", when: null, text: "Resolved: The United States federal government should significantly strengthen its protection of domestic intellectual property rights in copyrights, patents, and/or trademarks." },
    { season: "2023-24", when: null, text: "Resolved: The United States federal government should substantially increase fiscal redistribution in the United States by adopting a federal jobs guarantee, expanding Social Security, and/or providing a basic income." },
    { season: "2022-23", when: null, text: "Resolved: The United States federal government should substantially increase its security cooperation with the North Atlantic Treaty Organization in one or more of the following areas: artificial intelligence, biotechnology, cybersecurity." },
    { season: "2021-22", when: null, text: "Resolved: The United States federal government should substantially increase its protection of water resources in the United States." },
    { season: "2020-21", when: null, text: "Resolved: The United States federal government should enact substantial criminal justice reform in the United States in one or more of the following: forensic science, policing, sentencing." },
    { season: "2019-20", when: null, text: "Resolved: The United States federal government should substantially reduce Direct Commercial Sales and/or Foreign Military Sales of arms from the United States." },
    { season: "2018-19", when: null, text: "Resolved: The United States federal government should substantially reduce its restrictions on legal immigration to the United States." },
    { season: "2017-18", when: null, text: "Resolved: The United States federal government should substantially increase its funding and/or regulation of elementary and/or secondary education in the United States." },
    { season: "2016-17", when: null, text: "Resolved: The United States federal government should substantially increase its economic and/or diplomatic engagement with the People's Republic of China." },
    { season: "2015-16", when: null, text: "Resolved: The United States federal government should substantially curtail its domestic surveillance." },
    { season: "2014-15", when: null, text: "Resolved: The United States federal government should substantially increase its non-military exploration and/or development of the Earth's oceans." },
    { season: "2013-14", when: null, text: "Resolved: The United States federal government should substantially increase its economic engagement toward Cuba, Mexico or Venezuela." },
    { season: "2012-13", when: null, text: "Resolved: The United States federal government should substantially increase its transportation infrastructure investment in the United States." },
    { season: "2011-12", when: null, text: "Resolved: The United States federal government should substantially increase its exploration and/or development of space beyond the Earth's mesosphere." },
    { season: "2010-11", when: null, text: "Resolved: The United States federal government should substantially reduce its military and/or police presence in one or more of the following: South Korea, Japan, Afghanistan, Kuwait, Iraq, Turkey." },
    { season: "2009-10", when: null, text: "Resolved: The United States federal government should substantially increase social services for persons living in poverty in the United States." },
    { season: "2008-09", when: null, text: "Resolved: The United States federal government should substantially increase alternative energy incentives in the United States." },
    { season: "2007-08", when: null, text: "Resolved: The United States federal government should substantially increase its public health assistance to Sub-Saharan Africa." },
    { season: "2006-07", when: null, text: "Resolved: The United States federal government should establish a policy substantially increasing the number of persons serving in one or more of the following national service programs: AmeriCorps, Citizen Corps, Senior Corps, Peace Corps, Learn and Serve America, Armed Forces." },
    { season: "2005-06", when: null, text: "Resolved: The United States federal government should substantially decrease its authority either to detain without charge or to search without probable cause." },
    { season: "2004-05", when: null, text: "Resolved: That the United States federal government should establish a foreign policy substantially increasing its support of United Nations peacekeeping operations." },
    { season: "2003-04", when: null, text: "Resolved: That the United States federal government should establish an ocean policy substantially increasing protection of marine natural resources." },
    { season: "2002-03", when: null, text: "Resolved: That the United States federal government should substantially increase public health services for mental health care in the United States." },
    { season: "2001-02", when: null, text: "Resolved: That the United States federal government should establish a foreign policy significantly limiting the use of weapons of mass destruction." },
    { season: "2000-01", when: null, text: "Resolved: That the United States federal government should significantly increase protection of privacy in the United States in one or more of the following areas: employment, medical records, consumer information, search and seizure." },
    { season: "1999-00", when: null, text: "Resolved: That the federal government should establish an education policy to significantly increase academic achievement in secondary schools in the United States." },
    { season: "1998-99", when: null, text: "Resolved: That the United States should substantially change its foreign policy toward Russia." },
    { season: "1997-98", when: null, text: "Resolved: That the federal government should establish a policy to substantially increase renewable energy use in the United States." },
    { season: "1996-97", when: null, text: "Resolved: That the federal government should establish a program to substantially reduce juvenile crime in the United States." },
    { season: "1995-96", when: null, text: "Resolved: That the United States government should substantially change its foreign policy toward the People's Republic of China." },
    { season: "1994-95", when: null, text: "Resolved: That the United States government should substantially strengthen regulation of immigration to the United States." },
    { season: "1993-94", when: null, text: "Resolved: That the federal government should guarantee comprehensive national health insurance to all United States citizens." },
    { season: "1992-93", when: null, text: "Resolved: That the United States government should reduce worldwide pollution through its trade and/or aid policies." },
    { season: "1991-92", when: null, text: "Resolved: That the federal government should significantly increase social services to homeless individuals in the United States." },
    { season: "1990-91", when: null, text: "Resolved: That the United States government should significantly increase space exploration beyond the Earth's mesosphere." },
    { season: "1989-90", when: null, text: "Resolved: That the federal government should adopt a nationwide policy to decrease overcrowding in prisons and jails in the United States." },
    { season: "1988-89", when: null, text: "Resolved: That the federal government should implement a comprehensive program to guarantee retirement security for United States citizens over age 65." },
    { season: "1987-88", when: null, text: "Resolved: That the United States government should adopt a policy to increase political stability in Latin America." },
    { season: "1986-87", when: null, text: "Resolved: That the federal government should implement a comprehensive long-term agricultural policy in the United States." },
    { season: "1985-86", when: null, text: "Resolved: That the federal government should establish a comprehensive national policy to protect the quality of water in the United States." },
    { season: "1984-85", when: null, text: "Resolved: That the federal government should provide employment for all employable United States citizens living in poverty." },
    { season: "1983-84", when: null, text: "Resolved: That the United States should establish uniform rules governing the procedure of all criminal courts in the nation." },
    { season: "1982-83", when: null, text: "Resolved: That the United States should significantly curtail its arms sales to other countries." },
    { season: "1981-82", when: null, text: "Resolved: That the federal government should establish minimum educational standards for elementary and secondary schools in the United States." },
    { season: "1980-81", when: null, text: "Resolved: That the federal government should initiate and enforce safety guarantees on consumer goods." },
    { season: "1979-80", when: null, text: "Resolved: That the United States should significantly change its foreign trade policies." },
    { season: "1978-79", when: null, text: "Resolved: That the federal government should establish a comprehensive program to significantly increase the energy independence of the United States." },
    { season: "1977-78", when: null, text: "Resolved: That the federal government should establish a comprehensive program to regulate the health care system in the United States." },
    { season: "1976-77", when: null, text: "Resolved: That a comprehensive program of penal reform should be adopted throughout the United States." },
    { season: "1975-76", when: null, text: "Resolved: That the development and allocation of scarce world resources should be controlled by an international organization." },
    { season: "1974-75", when: null, text: "Resolved: That the United States should significantly change the method of selecting presidential and vice-presidential candidates." },
    { season: "1973-74", when: null, text: "Resolved: That the federal government should guarantee a minimum annual income to each family unit." },
    { season: "1972-73", when: null, text: "Resolved: That governmental financial support for all public and secondary education in the United States be provided exclusively by the federal government." },
    { season: "1971-72", when: null, text: "Resolved: That the jury system in the United States should be significantly changed." },
    { season: "1970-71", when: null, text: "Resolved: That the federal government should establish, finance, and administer programs to control air and/or water pollution in the United States." },
    { season: "1969-70", when: null, text: "Resolved: That Congress should prohibit unilateral United States military intervention in foreign countries." },
    { season: "1968-69", when: null, text: "Resolved: That the United States should establish a system of compulsory service by all citizens." },
    { season: "1967-68", when: null, text: "Resolved: That Congress should establish uniform regulations to control criminal investigation procedures." },
    { season: "1966-67", when: null, text: "Resolved: That the foreign aid program of the United States should be limited to non-military assistance." },
    { season: "1965-66", when: null, text: "Resolved: That the federal government should adopt a program of compulsory arbitration in labor-management disputes in basic industries." },
    { season: "1964-65", when: null, text: "Resolved: That nuclear weapons should be controlled by an international organization." },
    { season: "1963-64", when: null, text: "Resolved: That Social Security benefits should be extended to include complete medical care." },
    { season: "1962-63", when: null, text: "Resolved: That the United States should promote a Common Market for the western hemisphere." },
    { season: "1961-62", when: null, text: "Resolved: That the federal government should equalize educational opportunity by means of grants to the states for public elementary and secondary education." },
    { season: "1960-61", when: null, text: "Resolved: That the United Nations should be significantly strengthened." },
    { season: "1959-60", when: null, text: "Resolved: That the federal government should substantially increase its regulation of labor unions." },
    { season: "1958-59", when: null, text: "Resolved: That the United States should adopt the essential features of the British system of education." },
    { season: "1957-58", when: null, text: "Resolved: That United States foreign aid should be substantially increased." },
    { season: "1956-57", when: null, text: "Resolved: That the federal government should sustain the prices of major agricultural products at not less than 90% of parity." },
    { season: "1955-56", when: null, text: "Resolved: That governmental subsidies should be granted according to need to high school graduates who qualify for additional training." },
    { season: "1954-55", when: null, text: "Resolved: That the federal government should initiate a policy of free trade among nations friendly to the United States." },
    { season: "1953-54", when: null, text: "Resolved: That the President of the United States should be elected by the direct vote of the people." },
    { season: "1952-53", when: null, text: "Resolved: That the Atlantic Pact nations should form a federal union." },
    { season: "1951-52", when: null, text: "Resolved: That all American citizens should be subject to conscription for essential service in time of war." },
    { season: "1950-51", when: null, text: "Resolved: That the American people should reject the welfare state." },
    { season: "1949-50", when: null, text: "Resolved: That the president of the United States should be elected by the direct vote of the people." },
    { season: "1948-49", when: null, text: "Resolved: That the United States now be revised into a Federal World Government." },
    { season: "1947-48", when: null, text: "Resolved: That the federal government should require arbitration of labor disputes in all basic American industries." },
    { season: "1946-47", when: null, text: "Resolved: That the federal government should provide a system of complete medical care available to all citizens at public expense." },
    { season: "1945-46", when: null, text: "Resolved: That every able-bodied male citizen of the United States should have one year of full-time military training before attaining age 24." },
    { season: "1944-45", when: null, text: "Resolved: That the legal voting age should be reduced to eighteen years." },
    { season: "1943-44", when: null, text: "Resolved: That the United States should join in reconstituting the League of Nations." },
    { season: "1942-43", when: null, text: "Resolved: That a federal world government should be established." },
    { season: "1941-42", when: null, text: "Resolved: That every able-bodied male citizen in the United States should be required to have one year of full-time military training before attaining the present draft age." },
    { season: "1940-41", when: null, text: "Resolved: That the power of the federal government should be increased." },
    { season: "1939-40", when: null, text: "Resolved: That the federal government should own and operate the railroads." },
    { season: "1938-39", when: null, text: "Resolved: That the United States should establish an alliance with Great Britain." },
    { season: "1937-38", when: null, text: "Resolved: That the several states should adopt a unicameral system of legislation." },
    { season: "1936-37", when: null, text: "Resolved: That all electric utilities should be governmentally owned and operated." },
    { season: "1935-36", when: null, text: "Resolved: That the several states should enact legislation providing for a system of complete medical service available to all citizens at public expense." },
    { season: "1934-35", when: null, text: "Resolved: That the federal government should adopt the policy of equalizing educational opportunity throughout the nation by means of annual grants to the several states for public elementary and secondary education." },
    { season: "1933-34", when: null, text: "Resolved: That the United States should adopt the essential features of the British system of radio control and operation." },
    { season: "1932-33", when: null, text: "Resolved: That at least one half of all state and local revenues should be derived from sources other than tangible property." },
    { season: "1931-32", when: null, text: "Resolved: That the several states should enact legislation providing for compulsory unemployment insurance." },
    { season: "1930-31", when: null, text: "Resolved: That chain stores are detrimental to the best interests of the American public." },
    { season: "1929-30", when: null, text: "Resolved: That installment buying of personal property as now practiced in the United States is both socially and economically desirable." },
    { season: "1928-29", when: null, text: "Resolved: That the English cabinet method of legislation is more efficient than the committee system is in the United States." },
    { season: "1927-28", when: null, text: "Resolved: That a federal department of education should be created with a secretary in the president's cabinet." },
  ],
}
