// Thin wrapper around NVIDIA's hosted NIM API (OpenAI-compatible Chat
// Completions) — every response is generated by Nemotron 3 Super, grounded
// in CROSS.md + corpus material selected by buildSystemPrompt() in
// prompt.mjs. There is no fallback provider.
//
// Multi-model routing: callers pass a model *tier* ("opus" | "sonnet" |
// "haiku") chosen per task in server.mjs; this module owns the mapping to
// concrete model ids so they still live in exactly one place. NVIDIA_BASE_URL
// lets production point at a different OpenAI-compatible host (OpenRouter,
// Together, a self-hosted NIM) later with no code change.

import OpenAI from "openai";

let client;

function getClient() {
  if (!client) {
    client = new OpenAI({
      apiKey: process.env.NVIDIA_API_KEY,
      baseURL: process.env.NVIDIA_BASE_URL || "https://integrate.api.nvidia.com/v1",
    });
  }
  return client;
}

const MODEL_TIERS = {
  opus: process.env.NVIDIA_MODEL_OPUS || "nvidia/nemotron-3-super-120b-a12b",
  sonnet: process.env.NVIDIA_MODEL_SONNET || "nvidia/nemotron-3-super-120b-a12b",
  haiku: process.env.NVIDIA_MODEL_HAIKU || "nvidia/nemotron-3-super-120b-a12b",
};
const DEFAULT_TIER = "opus";
const VISION_MODEL = process.env.NVIDIA_MODEL_VISION || "meta/llama-3.2-11b-vision-instruct";

function resolveModel(model) {
  return MODEL_TIERS[model] ?? model ?? MODEL_TIERS[DEFAULT_TIER];
}

// One line per completed request so cost per route is observable.
function logUsage(label, model, usage) {
  if (!usage) return;
  console.log(`[ai] ${label} model=${model} in=${usage.prompt_tokens} out=${usage.completion_tokens}`);
}

export function hasCredentials() {
  return Boolean(process.env.NVIDIA_API_KEY);
}

export function missingCredentialsError() {
  return "NVIDIA_API_KEY is not set. Add it to .env.";
}

// --- one-shot text/JSON completion (stress-test, strategy-mode, summarize-round) ---

export async function completeText({ system, prompt, maxTokens, jsonSchema, model, temperature }) {
  if (!hasCredentials()) throw new Error(missingCredentialsError());
  const resolvedModel = resolveModel(model);
  const req = {
    model: resolvedModel,
    max_tokens: maxTokens,
    ...(Number.isFinite(temperature) ? { temperature } : {}),
    messages: [...(system ? [{ role: "system", content: system }] : []), { role: "user", content: prompt }],
    // Thinking off, same as streamChat: invisible reasoning ate most of
    // max_tokens on drill scenarios and truncated the JSON, at 2-4x the
    // latency.
    chat_template_kwargs: { enable_thinking: false },
  };
  // Structured outputs: constrain the response to a JSON schema so the API
  // guarantees valid JSON — prompt-only JSON breaks on unescaped quotes in
  // long string values (e.g. quoted speech lines in drill grading).
  if (jsonSchema) req.response_format = { type: "json_schema", json_schema: { name: "response", schema: jsonSchema, strict: true } };
  // Every caller parses this text as JSON — a response cut off at the token
  // limit is guaranteed-invalid. Large inputs legitimately produce longer
  // analyses (a big case means more stress-test cards), so retry once with
  // double the budget before failing loudly.
  for (let attempt = 0; ; attempt++) {
    const response = await getClient().chat.completions.create(req);
    logUsage("completeText", resolvedModel, response.usage);
    if (response.choices[0].finish_reason !== "length") {
      return response.choices[0].message.content ?? "";
    }
    if (attempt >= 1 || req.max_tokens >= 24000) {
      throw new Error(`model response was truncated at the ${req.max_tokens}-token limit`);
    }
    req.max_tokens = Math.min(req.max_tokens * 2, 24000);
    console.warn(`[ai] completeText truncated at ${maxTokens} tokens — retrying at ${req.max_tokens}`);
  }
}

// --- streaming chat with tool support ---

// One-shot image captioning via a separate NVIDIA-hosted vision model —
// Nemotron 3 Super is text-only, so image attachments are described in
// words before they ever reach it.
async function describeImage({ mediaType, data }) {
  const res = await getClient().chat.completions.create({
    model: VISION_MODEL,
    max_tokens: 500,
    messages: [
      {
        role: "user",
        content: [
          {
            type: "text",
            text: "Describe this image for a debate coach — capture any visible text, diagrams, flow structure, or case content verbatim where possible.",
          },
          { type: "image_url", image_url: { url: `data:${mediaType};base64,${data}` } },
        ],
      },
    ],
  });
  return res.choices[0].message.content ?? "";
}

// Flattens one message's content down to a plain string, describing any
// image blocks (the frontend still builds Anthropic-shaped attachment
// blocks — see coach-screen.tsx) since Nemotron can't see them directly.
async function flattenMessageContent(content) {
  if (typeof content === "string") return content;
  if (!Array.isArray(content)) return "";
  const parts = await Promise.all(
    content.map(async (block) => {
      if (block.type === "text") return block.text;
      if (block.type === "image") {
        try {
          const caption = await describeImage({ mediaType: block.source.media_type, data: block.source.data });
          return `[Image attached — described]: ${caption}`;
        } catch (err) {
          console.error("[ai] image captioning failed:", err);
          return "[Image attached — visual analysis unavailable]";
        }
      }
      if (block.type === "document") {
        // PDFs are now extracted to text at upload time (server.mjs) instead
        // of sent as raw bytes — this only fires for stale pre-swap chat
        // history still held in the browser's localStorage.
        return "[PDF attachment from a previous session — please re-upload]";
      }
      return "";
    })
  );
  return parts.filter(Boolean).join("\n\n");
}

// Kept as a pass-through name (rather than inlined at call sites) so the
// shape of `conversation` stays decoupled from how it's ultimately sent to
// the API. Also the one place that converts the frontend's Anthropic-shaped
// attachment blocks into Nemotron-safe plain-text content.
export async function prepareConversation(system, messages) {
  if (!hasCredentials()) throw new Error(missingCredentialsError());
  return Promise.all(messages.map(async (m) => ({ ...m, content: await flattenMessageContent(m.content) })));
}

/**
 * Streams one assistant turn. Returns:
 *   { assistantMessage, toolCalls: [{id, name, input}], isToolUse }
 * `assistantMessage` should be appended to `conversation` as-is before the
 * next call (streamChat or appendToolResults).
 */
export async function streamChat({ system, conversation, tools, toolChoice, maxTokens, onText, model, temperature, enableThinking = true }) {
  if (!hasCredentials()) throw new Error(missingCredentialsError());
  const resolvedModel = resolveModel(model);
  const openaiTools = tools?.map((t) => ({
    type: "function",
    function: { name: t.name, description: t.description, parameters: t.input_schema },
  }));

  const stream = await getClient().chat.completions.create({
    model: resolvedModel,
    max_tokens: maxTokens,
    ...(Number.isFinite(temperature) ? { temperature } : {}),
    // Reasoning is a Time-to-First-Token tradeoff. With thinking ON the model
    // emits `reasoning_content` deltas (a separate field from `content`, always
    // discarded below — the debater must never see them) BEFORE the first
    // visible token, which delays TTFT by the length of that hidden pass. ON
    // measurably sharpens tool triggering; OFF streams the answer sooner. The
    // caller decides per route — chat defaults OFF for latency (see
    // CHAT_ENABLE_THINKING in server.mjs); other callers keep the historical ON.
    chat_template_kwargs: { enable_thinking: enableThinking },
    messages: [{ role: "system", content: system }, ...conversation],
    ...(openaiTools ? { tools: openaiTools } : {}),
    // tool_choice "none" forces a text answer while keeping the tool
    // definitions present (required when the history has tool_calls).
    ...(toolChoice?.type === "none" ? { tool_choice: "none" } : {}),
    stream: true,
    stream_options: { include_usage: true },
  });

  let text = "";
  const toolCallsByIndex = new Map();
  let usage = null;
  let finishReason = null;

  for await (const chunk of stream) {
    const choice = chunk.choices?.[0];
    if (choice?.finish_reason) finishReason = choice.finish_reason;
    if (chunk.usage) usage = chunk.usage;
    const delta = choice?.delta;
    if (!delta) continue;
    if (delta.content) {
      text += delta.content;
      onText(delta.content);
    }
    // KNOWN ISSUE (pre-existing, not yet fixed): Nemotron occasionally emits a
    // literal `<tool_call>`/`</tool_call>` text token inside delta.content
    // itself — alongside, not instead of, a proper native delta.tool_calls
    // entry — which streams straight through onText and can appear in the
    // debater-visible reply. Reproduced 2026-09 testing the web_search tool
    // (unrelated to that feature — this is a streamChat/model-output parsing
    // gap that would surface with any tool). Needs its own investigation into
    // whether it's a vLLM/NIM chat-template quirk worth stripping here before
    // onText, rather than a fix bundled into an unrelated task.
    // delta.reasoning_content intentionally ignored — thinking never reaches onText.
    if (delta.tool_calls) {
      for (const tc of delta.tool_calls) {
        const existing = toolCallsByIndex.get(tc.index) ?? { id: "", name: "", argsBuf: "" };
        if (tc.id) existing.id = tc.id;
        if (tc.function?.name) existing.name = tc.function.name;
        if (tc.function?.arguments) existing.argsBuf += tc.function.arguments;
        toolCallsByIndex.set(tc.index, existing);
      }
    }
  }

  logUsage("streamChat", resolvedModel, usage);

  const toolCalls = [...toolCallsByIndex.values()].map((tc) => {
    let input = {};
    try {
      input = tc.argsBuf ? JSON.parse(tc.argsBuf) : {};
    } catch (err) {
      console.error(`[ai] failed to parse tool arguments for ${tc.name}:`, tc.argsBuf, err);
    }
    return { id: tc.id, name: tc.name, input };
  });

  const assistantMessage = {
    role: "assistant",
    content: text || null,
    ...(toolCalls.length
      ? { tool_calls: toolCalls.map((tc) => ({ id: tc.id, type: "function", function: { name: tc.name, arguments: JSON.stringify(tc.input) } })) }
      : {}),
  };

  return {
    assistantMessage,
    toolCalls,
    isToolUse: toolCalls.length > 0 || finishReason === "tool_calls",
  };
}

// Appends the tool-result messages that report tool outcomes back to the
// model — OpenAI wants one `role:"tool"` message per call (unlike
// Anthropic's single grouped tool_result user message).
export function appendToolResults(conversation, toolCalls, results) {
  if (!hasCredentials()) throw new Error(missingCredentialsError());
  for (const tc of toolCalls) {
    const result = results.get(tc.id);
    conversation.push({
      role: "tool",
      tool_call_id: tc.id,
      content: typeof result.content === "string" ? result.content : JSON.stringify(result.content),
    });
  }
  return conversation;
}
