create table if not exists judge_paradigm_cache (
  id             bigint generated by default as identity primary key,
  cache_key      text not null unique,        -- 'id:<judge_id>' or 'name:<normalized name>'
  judge_id       text,
  name           text not null,
  source         text not null default 'tabroom_fallback'
                   check (source in ('tabroom_fallback', 'tournaments_tech')),
  tabroom_url    text,
  paradigm_text  text not null,
  paradigm_hash  text not null,                -- sha256 hex
  summary_json   jsonb not null,               -- StructuredJudgeSummary
  tags           text[] not null default '{}',
  summary_model  text,
  scraped_at     timestamptz not null default now(),
  summarized_at  timestamptz not null default now(),
  created_at     timestamptz not null default now(),
  updated_at     timestamptz not null default now()
);

create index if not exists judge_paradigm_cache_judge_id_idx
  on judge_paradigm_cache (judge_id) where judge_id is not null;

alter table judge_paradigm_cache enable row level security;
-- No policies: only ever touched via service_role key from server (bypasses RLS).
